name: Build APK with Buildozer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 python3-pip openjdk-11-jdk zip unzip git

      - name: Install Buildozer & dependencies
        run: |
          python3 -m pip install --upgrade buildozer
          sudo apt-get install -y libgl1-mesa-dev libgles2-mesa-dev \
               androidsdk android-sdk-platform-23 android-sdk-build-tools-30.0.3 \
               zlib1g-dev libncurses5:i386 libstdc++6:i386 libgcc1:i386

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: galleons-apk
          path: bin/*.apk
