name: Build APK with Buildozer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libtinfo5
        pip install --upgrade pip
        pip install cython buildozer

    - name: Set up Android SDK/NDK manually
      run: |
        mkdir -p ~/.buildozer/android/platform
        cd ~/.buildozer/android/platform
        
        # Download and install Android Command Line Tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools cmdline-tools/latest
        rm cmdline-tools.zip
        
        # Set environment variables
        echo "ANDROID_SDK_ROOT=~/.buildozer/android/platform" >> $GITHUB_ENV
        echo "PATH=~/.buildozer/android/platform/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
        
        # Accept licenses (critical)
        yes | sdkmanager --licenses
        
        # Install NDK (version specified in your error log)
        sdkmanager --install "ndk;25.1.8937393" --channel=0

    - name: Build APK
      run: |
        buildozer android clean
        buildozer android debug
