name: Build APK with Buildozer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential git zip unzip openjdk-17-jdk
        pip install --upgrade pip
        pip install cython

    - name: Install buildozer
      run: |
        pip install buildozer

    - name: Build APK
      run: |
        buildozer android debug
