name: Build APK

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Builds can take time

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Best compatibility with Buildozer

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
            git zip unzip openjdk-17-jdk \
            autoconf libtool pkg-config zlib1g-dev \
            libncurses5-dev libtinfo5

    - name: Install Buildozer + Cython
      run: |
        pip install --upgrade pip wheel
        pip install buildozer cython

    - name: Pre-download Android tools
      run: |
        mkdir -p ~/.buildozer/android/platform
        cd ~/.buildozer/android/platform
        
        # Download SDK Command Line Tools (avoid flaky Buildozer downloads)
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-*.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools cmdline-tools/latest
        rm commandlinetools-linux-*.zip
        
        # Install NDK 25.1.8937393 (required for Android 12+)
        yes | ./cmdline-tools/latest/bin/sdkmanager --install "ndk;25.1.8937393"

    - name: Build APK
      run: |
        export ANDROID_SDK_ROOT="$HOME/.buildozer/android/platform"
        export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH"
        
        # Accept all licenses (critical)
        yes | sdkmanager --licenses
        
        # Build with verbose logging
        buildozer -v android debug
