name: Build APK with Buildozer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker container
        uses: addnab/docker-run-action@v3
        with:
          image: kivy/buildozer
          options: -v ${{ github.workspace }}:/workspace -w /workspace
          run: |
            apt-get update && apt-get install -y zip unzip
            buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: galleons-apk
          path: bin/*.apk
